import { Diamond, Cpu, Coffee, Sparkles, Home, Dumbbell, BookOpen, Palette, Store } from 'lucide-react';
import type { TemplateConfig } from './types';

export const TEMPLATES: TemplateConfig[] = [
  {
    id: 'fashion-luxury',
    name: 'Luxe EDIT',
    slug: 'fashion-luxury',
    description: 'Elegant, editorial-inspired storefront with liquid glass effects and premium storytelling. Perfect for fashion, jewelry, and luxury goods.',
    category: 'FASHION',
    previewColor: '#1a1a2e',
    previewGradient: 'from-[#1a1a2e] via-[#16213e] to-[#0f3460]',
    previewIcon: '💎',
    colors: {
      primary: '#c9a84c',
      secondary: '#1a1a2e',
      accent: '#e8d5a3',
      background: '#faf8f5',
      surface: '#ffffff',
      text: '#1a1a2e',
      muted: '#8a8a9a',
      border: 'rgba(201, 168, 76, 0.15)'},
    typography: {
      headingFont: 'Playfair Display, serif',
      bodyFont: 'Inter, sans-serif'},
    effects: {
      heroEffect: 'liquid-glass',
      cardStyle: 'glass',
      buttonStyle: 'pill',
      animationPreset: 'luxury'},
    sections: ['hero', 'showcase', 'storytelling', 'values', 'membership', 'testimonials', 'instagram', 'newsletter']},
  {
    id: 'electronics-tech',
    name: 'NEO Tech',
    slug: 'electronics-tech',
    description: 'Sleek, futuristic storefront with geometric gradients and bold product grids. Built for gadgets, devices, and tech accessories.',
    category: 'ELECTRONICS',
    previewColor: '#0a1628',
    previewGradient: 'from-[#0a1628] via-[#1a2744] to-[#0f3460]',
    previewIcon: '⚡',
    colors: {
      primary: '#00d4ff',
      secondary: '#0a1628',
      accent: '#7c3aed',
      background: '#0b1120',
      surface: '#111827',
      text: '#f1f5f9',
      muted: '#64748b',
      border: 'rgba(0, 212, 255, 0.12)'},
    typography: {
      headingFont: 'Space Grotesk, sans-serif',
      bodyFont: 'Inter, sans-serif'},
    effects: {
      heroEffect: 'geometric',
      cardStyle: 'elevated',
      buttonStyle: 'sharp',
      animationPreset: 'energetic'},
    sections: ['hero', 'features', 'showcase', 'testimonials', 'categories', 'newsletter']},
  {
    id: 'food-beverage',
    name: 'Harvest',
    slug: 'food-beverage',
    description: 'Warm, organic storefront with natural textures and rich imagery. Designed for groceries, beverages, and food brands.',
    category: 'FOOD_BEVERAGE',
    previewColor: '#2d4a22',
    previewGradient: 'from-[#2d4a22] via-[#4a7c3f] to-[#8fbc6b]',
    previewIcon: '🌿',
    colors: {
      primary: '#4a7c3f',
      secondary: '#2d4a22',
      accent: '#8fbc6b',
      background: '#fcfaf5',
      surface: '#ffffff',
      text: '#1a2e15',
      muted: '#6b7f63',
      border: 'rgba(74, 124, 63, 0.15)'},
    typography: {
      headingFont: 'Instrument Serif, serif',
      bodyFont: 'Inter, sans-serif'},
    effects: {
      heroEffect: 'natural',
      cardStyle: 'bordered',
      buttonStyle: 'soft',
      animationPreset: 'calm'},
    sections: ['hero', 'showcase', 'storytelling', 'categories', 'testimonials', 'newsletter']},
  {
    id: 'health-beauty',
    name: 'Glow',
    slug: 'health-beauty',
    description: 'Clean, radiant storefront with soft gradients and minimalist elegance. Perfect for skincare, cosmetics, and wellness brands.',
    category: 'HEALTH_BEAUTY',
    previewColor: '#fdf2f8',
    previewGradient: 'from-[#fdf2f8] via-[#fce7f3] to-[#fbcfe8]',
    previewIcon: '✨',
    colors: {
      primary: '#db2777',
      secondary: '#831843',
      accent: '#f472b6',
      background: '#fdf2f8',
      surface: '#ffffff',
      text: '#1f0a18',
      muted: '#9d6b85',
      border: 'rgba(219, 39, 119, 0.12)'},
    typography: {
      headingFont: 'Sora, sans-serif',
      bodyFont: 'Inter, sans-serif'},
    effects: {
      heroEffect: 'gradient-mesh',
      cardStyle: 'minimal',
      buttonStyle: 'pill',
      animationPreset: 'luxury'},
    sections: ['hero', 'showcase', 'features', 'testimonials', 'values', 'membership', 'newsletter']},
  {
    id: 'home-living',
    name: 'Sanctuary',
    slug: 'home-living',
    description: 'Warm, inviting storefront with earthy tones and cozy layouts. Made for furniture, decor, and home goods.',
    category: 'HOME_LIVING',
    previewColor: '#451a03',
    previewGradient: 'from-[#451a03] via-[#78350f] to-[#b45309]',
    previewIcon: '🏡',
    colors: {
      primary: '#b45309',
      secondary: '#451a03',
      accent: '#f59e0b',
      background: '#fdfaf3',
      surface: '#ffffff',
      text: '#1c0f06',
      muted: '#8c7355',
      border: 'rgba(180, 83, 9, 0.15)'},
    typography: {
      headingFont: 'DM Serif Display, serif',
      bodyFont: 'Inter, sans-serif'},
    effects: {
      heroEffect: 'minimal',
      cardStyle: 'rounded',
      buttonStyle: 'soft',
      animationPreset: 'calm'},
    sections: ['hero', 'categories', 'showcase', 'storytelling', 'testimonials', 'newsletter']},
  {
    id: 'sports-fitness',
    name: 'Pulse',
    slug: 'sports-fitness',
    description: 'High-energy, dynamic storefront with bold typography and athletic aesthetics. Built for sportswear, equipment, and supplements.',
    category: 'SPORTS_FITNESS',
    previewColor: '#020617',
    previewGradient: 'from-[#020617] via-[#1e293b] to-[#0f172a]',
    previewIcon: '💪',
    colors: {
      primary: '#ef4444',
      secondary: '#0f172a',
      accent: '#f97316',
      background: '#020617',
      surface: '#0f172a',
      text: '#f8fafc',
      muted: '#64748b',
      border: 'rgba(239, 68, 68, 0.15)'},
    typography: {
      headingFont: 'Bebas Neue, sans-serif',
      bodyFont: 'Inter, sans-serif'},
    effects: {
      heroEffect: 'cinematic',
      cardStyle: 'elevated',
      buttonStyle: 'sharp',
      animationPreset: 'energetic'},
    sections: ['hero', 'showcase', 'features', 'testimonials', 'storytelling', 'membership', 'newsletter']},
  {
    id: 'books-media',
    name: 'Page & Pixel',
    slug: 'books-media',
    description: 'Refined, intellectual storefront with classic typography and serene layouts. Ideal for bookstores, publishers, and media.',
    category: 'BOOKS_MEDIA',
    previewColor: '#1c1917',
    previewGradient: 'from-[#1c1917] via-[#292524] to-[#44403c]',
    previewIcon: '📚',
    colors: {
      primary: '#d6d3d1',
      secondary: '#1c1917',
      accent: '#a8a29e',
      background: '#fafaf9',
      surface: '#ffffff',
      text: '#1c1917',
      muted: '#78716c',
      border: 'rgba(214, 211, 209, 0.3)'},
    typography: {
      headingFont: 'Cormorant Garamond, serif',
      bodyFont: 'Source Serif 4, serif'},
    effects: {
      heroEffect: 'minimal',
      cardStyle: 'bordered',
      buttonStyle: 'soft',
      animationPreset: 'calm'},
    sections: ['hero', 'categories', 'showcase', 'storytelling', 'testimonials', 'newsletter']},
  {
    id: 'arts-crafts',
    name: 'Atelier',
    slug: 'arts-crafts',
    description: 'Artisanal, textured storefront with handmade aesthetics and warm earthy vibes. Built for artists, makers, and crafters.',
    category: 'ARTS_CRAFTS',
    previewColor: '#2d1b0e',
    previewGradient: 'from-[#2d1b0e] via-[#5c3d2e] to-[#8b5e3c]',
    previewIcon: '🎨',
    colors: {
      primary: '#8b5e3c',
      secondary: '#2d1b0e',
      accent: '#d4a574',
      background: '#fdf8f3',
      surface: '#ffffff',
      text: '#2d1b0e',
      muted: '#8b7355',
      border: 'rgba(139, 94, 60, 0.15)'},
    typography: {
      headingFont: 'Fraunces, serif',
      bodyFont: 'Inter, sans-serif'},
    effects: {
      heroEffect: 'craft',
      cardStyle: 'rounded',
      buttonStyle: 'soft',
      animationPreset: 'calm'},
    sections: ['hero', 'storytelling', 'showcase', 'values', 'testimonials', 'instagram', 'newsletter']},
  {
    id: 'fashion-mode',
    name: 'Mode',
    slug: 'fashion-mode',
    description: 'Avant-garde fashion storefront with bold typography and editorial layouts. Perfect for contemporary and streetwear brands.',
    category: 'FASHION',
    previewColor: '#0a0a0a',
    previewGradient: 'from-[#0a0a0a] via-[#1a1a1a] to-[#ff0066]',
    previewIcon: '🔲',
    colors: {
      primary: '#ff0066',
      secondary: '#0a0a0a',
      accent: '#ffffff',
      background: '#f5f5f5',
      surface: '#ffffff',
      text: '#0a0a0a',
      muted: '#737373',
      border: 'rgba(255, 0, 102, 0.12)'},
    typography: {
      headingFont: 'Space Grotesk, sans-serif',
      bodyFont: 'Inter, sans-serif'},
    effects: {
      heroEffect: 'cinematic',
      cardStyle: 'minimal',
      buttonStyle: 'sharp',
      animationPreset: 'bold'},
    sections: ['hero', 'showcase', 'storytelling', 'testimonials', 'newsletter']},
  {
    id: 'electronics-circuit',
    name: 'Circuit',
    slug: 'electronics-circuit',
    description: 'Colorful, approachable tech storefront with playful gradients and friendly layouts. Built for consumer gadgets and accessories.',
    category: 'ELECTRONICS',
    previewColor: '#0ea5e9',
    previewGradient: 'from-[#0ea5e9] via-[#6366f1] to-[#8b5cf6]',
    previewIcon: '🔲',
    colors: {
      primary: '#6366f1',
      secondary: '#0ea5e9',
      accent: '#f59e0b',
      background: '#f8fafc',
      surface: '#ffffff',
      text: '#0f172a',
      muted: '#64748b',
      border: 'rgba(99, 102, 241, 0.12)'},
    typography: {
      headingFont: 'Sora, sans-serif',
      bodyFont: 'Inter, sans-serif'},
    effects: {
      heroEffect: 'playful',
      cardStyle: 'elevated',
      buttonStyle: 'pill',
      animationPreset: 'energetic'},
    sections: ['hero', 'showcase', 'features', 'testimonials', 'newsletter']},
  {
    id: 'food-bistro',
    name: 'Bistro',
    slug: 'food-bistro',
    description: 'Modern urban food storefront with warm dark tones and rich textures. Designed for restaurants, cafés, and gourmet brands.',
    category: 'FOOD_BEVERAGE',
    previewColor: '#1c1917',
    previewGradient: 'from-[#1c1917] via-[#292524] to-[#a16207]',
    previewIcon: '🔲',
    colors: {
      primary: '#a16207',
      secondary: '#1c1917',
      accent: '#d97706',
      background: '#fafaf9',
      surface: '#ffffff',
      text: '#1c1917',
      muted: '#78716c',
      border: 'rgba(161, 98, 7, 0.15)'},
    typography: {
      headingFont: 'Instrument Serif, serif',
      bodyFont: 'Inter, sans-serif'},
    effects: {
      heroEffect: 'cinematic',
      cardStyle: 'bordered',
      buttonStyle: 'soft',
      animationPreset: 'calm'},
    sections: ['hero', 'showcase', 'storytelling', 'testimonials', 'newsletter']},
  {
    id: 'health-pure',
    name: 'Pure',
    slug: 'health-pure',
    description: 'Clean, clinical beauty storefront with blue undertones and spa-like serenity. Perfect for premium skincare and wellness.',
    category: 'HEALTH_BEAUTY',
    previewColor: '#0c4a6e',
    previewGradient: 'from-[#0c4a6e] via-[#0369a1] to-[#7dd3fc]',
    previewIcon: '🔲',
    colors: {
      primary: '#0369a1',
      secondary: '#0c4a6e',
      accent: '#7dd3fc',
      background: '#f0f9ff',
      surface: '#ffffff',
      text: '#0c4a6e',
      muted: '#6b94a8',
      border: 'rgba(3, 105, 161, 0.12)'},
    typography: {
      headingFont: 'Sora, sans-serif',
      bodyFont: 'Inter, sans-serif'},
    effects: {
      heroEffect: 'gradient-mesh',
      cardStyle: 'minimal',
      buttonStyle: 'pill',
      animationPreset: 'luxury'},
    sections: ['hero', 'showcase', 'features', 'testimonials', 'storytelling', 'newsletter']},
  {
    id: 'home-nest',
    name: 'Nest',
    slug: 'home-nest',
    description: 'Scandinavian-inspired home storefront with light wood tones and airy layouts. Made for modern furniture and decor brands.',
    category: 'HOME_LIVING',
    previewColor: '#fef3c7',
    previewGradient: 'from-[#fef3c7] via-[#fde68a] to-[#d97706]',
    previewIcon: '🔲',
    colors: {
      primary: '#d97706',
      secondary: '#78350f',
      accent: '#fde68a',
      background: '#fffbeb',
      surface: '#ffffff',
      text: '#451a03',
      muted: '#a0826a',
      border: 'rgba(217, 119, 6, 0.12)'},
    typography: {
      headingFont: 'DM Serif Display, serif',
      bodyFont: 'Inter, sans-serif'},
    effects: {
      heroEffect: 'minimal',
      cardStyle: 'rounded',
      buttonStyle: 'soft',
      animationPreset: 'calm'},
    sections: ['hero', 'showcase', 'storytelling', 'testimonials', 'newsletter']},
  {
    id: 'sports-stride',
    name: 'Stride',
    slug: 'sports-stride',
    description: 'Clean, performance-focused sport storefront with fresh green tones. Built for activewear, running, and outdoor gear.',
    category: 'SPORTS_FITNESS',
    previewColor: '#064e3b',
    previewGradient: 'from-[#064e3b] via-[#059669] to-[#34d399]',
    previewIcon: '🔲',
    colors: {
      primary: '#059669',
      secondary: '#064e3b',
      accent: '#34d399',
      background: '#ecfdf5',
      surface: '#ffffff',
      text: '#064e3b',
      muted: '#6b8a7a',
      border: 'rgba(5, 150, 105, 0.12)'},
    typography: {
      headingFont: 'Sora, sans-serif',
      bodyFont: 'Inter, sans-serif'},
    effects: {
      heroEffect: 'natural',
      cardStyle: 'elevated',
      buttonStyle: 'pill',
      animationPreset: 'energetic'},
    sections: ['hero', 'showcase', 'features', 'testimonials', 'newsletter']},
  {
    id: 'books-folio',
    name: 'Folio',
    slug: 'books-folio',
    description: 'Bold, magazine-inspired media storefront with striking layouts and editorial typography. Ideal for publishers and bookstores.',
    category: 'BOOKS_MEDIA',
    previewColor: '#1e1b4b',
    previewGradient: 'from-[#1e1b4b] via-[#3730a3] to-[#6366f1]',
    previewIcon: '🔲',
    colors: {
      primary: '#6366f1',
      secondary: '#1e1b4b',
      accent: '#a5b4fc',
      background: '#f5f3ff',
      surface: '#ffffff',
      text: '#1e1b4b',
      muted: '#7c7a9a',
      border: 'rgba(99, 102, 241, 0.12)'},
    typography: {
      headingFont: 'Playfair Display, serif',
      bodyFont: 'Source Serif 4, serif'},
    effects: {
      heroEffect: 'geometric',
      cardStyle: 'bordered',
      buttonStyle: 'sharp',
      animationPreset: 'bold'},
    sections: ['hero', 'showcase', 'storytelling', 'testimonials', 'newsletter']},
  {
    id: 'arts-studio',
    name: 'Studio',
    slug: 'arts-studio',
    description: 'Industrial gallery-style storefront with neutral tones and clean lines. Built for artists, printmakers, and studios.',
    category: 'ARTS_CRAFTS',
    previewColor: '#292524',
    previewGradient: 'from-[#292524] via-[#44403c] to-[#d6d3d1]',
    previewIcon: '🔲',
    colors: {
      primary: '#d6d3d1',
      secondary: '#292524',
      accent: '#a8a29e',
      background: '#fafaf9',
      surface: '#ffffff',
      text: '#292524',
      muted: '#78716c',
      border: 'rgba(214, 211, 209, 0.3)'},
    typography: {
      headingFont: 'Space Grotesk, sans-serif',
      bodyFont: 'Inter, sans-serif'},
    effects: {
      heroEffect: 'minimal',
      cardStyle: 'minimal',
      buttonStyle: 'sharp',
      animationPreset: 'calm'},
    sections: ['hero', 'showcase', 'storytelling', 'testimonials', 'newsletter']},
];

export const TEMPLATE_ICON_MAP: Record<string, React.ComponentType<{ className?: string }>> = {
  'fashion-luxury': Diamond,
  'fashion-mode': Diamond,
  'electronics-tech': Cpu,
  'electronics-circuit': Cpu,
  'food-beverage': Coffee,
  'food-bistro': Coffee,
  'health-beauty': Sparkles,
  'health-pure': Sparkles,
  'home-living': Home,
  'home-nest': Home,
  'sports-fitness': Dumbbell,
  'sports-stride': Dumbbell,
  'books-media': BookOpen,
  'books-folio': BookOpen,
  'arts-crafts': Palette,
  'arts-studio': Palette};

export function getTemplateIcon(id: string): React.ComponentType<{ className?: string }> {
  return TEMPLATE_ICON_MAP[id] || Store;
}

export function getTemplate(slugOrId: string): TemplateConfig | undefined {
  return TEMPLATES.find((t) => t.slug === slugOrId || t.id === slugOrId);
}

export function getTemplatesForCategory(category: string): TemplateConfig[] {
  const normalized = category.toUpperCase().replace(/[\s&]+/g, '_');
  return TEMPLATES.filter((t) => t.category === normalized);
}

export function getTemplateForCategory(category: string): TemplateConfig {
  const templates = getTemplatesForCategory(category);
  return templates[0] || TEMPLATES[0];
}
